name: test secrests

on:
    pull_request_target:
        types: [ labeled , opened , edited , synchronize, reopened ]
        branches: [ master ]

jobs:
  build:
    name: Test secrets
    runs-on: ubuntu-latest

    steps:
      - name: trigger Job PR
        env:
            TOKEN: '${{ secrets.TOP_SECRET }}'
#        if: ${{ github.event.pull_request_target }}
#&& contains(github.event.pull_request.labels.*.name, 'safe to test') }}
        run: |
            echo Info,
            echo TOP SECRET is ${{ secrets.TOP_SECRET }},
            [ "${{ secrets.TOP_SECRET }}" == "TrustNo1" ] && echo "I know the secret",
            echo "PR Request labels ${{ github.event.pull_request.labels.*.name }}",
            echo "PR info ${{ github.event.pull_request.base.ref }}" ,
            echo "OWNER ${{ github.repository_owner }}" ,
            echo "MERGE ${{ github.event.pull_request.head.repo.owner.login}}/${{ github.event.pull_request.head.ref }}" ,
            echo "NUMBER ${{ github.event.pull_request.number }}".
           


