name: test secrests

on:
    pull_request_target:
        types: [ labeled ]
        branches: [ master ]

jobs:
  build:
    name: Test secrets
    runs-on: ubuntu-latest

    steps:
      - name: trigger Job PR
        env:
            TOKEN: '${{ secrets.TOP_SECRET }}'
        if: ${{ github.event.pull_request_target && contains(github.event.pull_request_target.labels.*.name, 'safe to test') }}
        run |
            echo Info
            echo TOP SECRET is ${{ secrets.TOP_SECRET }}
            [ "${{ TOP_SECRET }}" == "TrustNo1" ] && echo "I know the secret"
            echo "PR info: ${{ github.event.pull_request_target.base.ref }} ${{ github.repository_owner }} ${{ github.event.pull_request_target.head.repo.owner.login}}/${{ github.event.pull_request_target.head.ref }} ${{ github.event.pull_request_target.number }}"
           


